apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-kringen-io
spec:
  # name of the tls secret to store
  # the generated certificate/key pair
  secretName: cert-kringen-io
  issuerRef:
    # Issuer Name
    # kubectl get issuer or kubectl get clusterissuer
    name: letsencrypt
    # The default value is Issuer (i.e.
    # a locally namespaced Issuer)
    kind: ClusterIssuer
  commonName: kringen.io
  dnsNames:
   # one or more fully-qualified domain names
   # can be defined here
  - kringen.io
  - "*.kringen.io"
  - locahost